GET http://localhost:8080/api/order

###


DELETE http://localhost:8080/api/order/200
Content-Type: application/json

{
    "creationDate": "2023-05-27T17:13:42.937Z[UTC]",
    "id": 110,
    "city": "Budapest",
    "courierId": 97,
    "houseNumber": "56546",
    "pizzas": [
      {
        "id": 2,
        "creationDate": "2023-05-20T12:27:05.86Z[UTC]",
        "creatorUser": {
          "id": 1,
          "createdAt": "2023-05-27T11:27:48.014Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "modificationDate": "2023-05-20T12:27:05.86Z[UTC]",
        "modifierUser": {
          "id": 1,
          "createdAt": "2023-05-27T11:27:48.014Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
         }
    }
    ],
        "street": "Alma",
    "streetType": "lugas"
}


###

POST http://localhost:8080/api/order/
Content-Type: application/json

{
  "model": {
    "creationDate": "2023-05-31T11:29:11.438Z[UTC]",
    "id": 220,
    "city": "asd",
    "courierId": 143,
    "houseNumber": "17/A",
    "pizzas": [
      {
        "id": 2,
        "creationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "creatorUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "modificationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "modifierUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "details": "Baconös pizza cheddar sajttal",
        "name": "Bacon-Cheddar",
        "price": 1790
      },
      {
        "id": 7,
        "creationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "creatorUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "modificationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "modifierUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "details": "Gyrosos pizza friss salátával és tzatzikivel",
        "name": "Gyrosos",
        "price": 1690
      },
      {
        "id": 8,
        "creationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "creatorUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "modificationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "modifierUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "details": "Margaréta pizza friss paradicsommal és bazsalikommal",
        "name": "Margaréta",
        "price": 1190
      },
      {
        "id": 9,
        "creationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "creatorUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "modificationDate": "2023-05-29T11:47:24.476Z[UTC]",
        "modifierUser": {
          "id": 1,
          "createdAt": "2023-05-29T11:46:08.641Z[UTC]",
          "orders": [],
          "password": "$2a$10$hpVQ8XuB/oCDSSEPGrVC7eTFoBXOGZExH.fpQSDe9pm1bs7wyWpdG",
          "role": "ADMIN",
          "username": "admin"
        },
        "details": "Hawaii pizza sonkával és ananásszal",
        "name": "Hawaii",
        "price": 1490
      }
    ],
    "street": "asdasd",
    "streetType": "asdasd"
  }
}